### ISSUE TITLE
dcm-set-acl

### ISSUE THREAD

**Issue by shaunsmarshall** [enStratus/mixcoatl#156]
dcm-set-acl -r xx -i  acl.json

Using K28.1 when i import a json file containing several acls , only 1 is being imported into DCM

[dcm@dcmmgt-na2-03 mixcoatl-master]$ dcm-get admin/Role/23
{
  "roles": [
    {
      "acl": [
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        }
      ],
      "customer": {
        "customerId": 200
      },
      "description": "test",
      "name": "test",
      "roleId": 23,
      "status": "ACTIVE"
    }
  ]
}

json file
----------------------------------
[dcm@dcmmgt-na2-03 mixcoatl-master]$ cat test.json
 {
      "acl": [
      {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "Create",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "Delete",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "ShareLocal",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "CreateVolume",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
         {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
         {
          "action": "SharePublic",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "SERVER"
        },
        {
          "action": "UnPause",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
         {
          "action": "ManageBilling",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ManageUsers",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Resume",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
         {
          "action": "Stop",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ViewLogs",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
         {
          "action": "ManageOwnership",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Pause",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
         {
          "action": "Suspend",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Image",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Terminate",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Reboot",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Monitor",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Start",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ViewPassword",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "VOLUME"
        },
         {
          "action": "Delete",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Snapshot",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Create",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Attach",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "ManageOwnership",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Detach",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "ManageBilling",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "IMAGE"
        },
        {
          "action": "ShareLocal",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "AccessPublic",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
         {
          "action": "SharePublic",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "DefineServerFromPublic",
          "qualifier": "ANY",
          "resourceType": "IMAGE"
        },
        {
          "action": "ManageBilling",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "ManageOwnership",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "Delete",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "DefineServer",
          "qualifier": "ANY",
          "resourceType": "IMAGE"
        },
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        }
      ]
}

------------------------------------------------------------------

**Comment by bdwilliams** [comment]
The API now expects a full ACL update instead of individual ACL appends to take place.

(venv)[brian:...om/bdwilliams/venv/mixcoatl]$ dcm-set-acl -r 2195 -i ~/Desktop/test.json                                                                                                   
URL: https://dcm.enstratius.com/api/enstratus/2014-07-30/admin/Role/2195
data = {"grant": [{"acl": [{"action": "Access", "resourceType": "SNAPSHOT", "qualifier": "ANY"}, {"action": "Create", "resourceType": "SNAPSHOT", "qualifier": "MINE"}, {"action": "Delete", "resourceType": "SNAPSHOT", "qualifier": "MINE"}, {"action": "ShareLocal", "resourceType": "SNAPSHOT", "qualifier": "MINE"}, {"action": "CreateVolume", "resourceType": "SNAPSHOT", "qualifier": "MINE"}, {"action": "Configure", "resourceType": "SNAPSHOT", "qualifier": "MINE"}, {"action": "SharePublic", "resourceType": "SNAPSHOT", "qualifier": "MINE"}, {"action": "Access", "resourceType": "SERVER", "qualifier": "ANY"}, {"action": "UnPause", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "ManageBilling", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "ManageUsers", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Resume", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Stop", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "ViewLogs", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "ManageOwnership", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Pause", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Suspend", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Image", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Terminate", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Reboot", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Monitor", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Start", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "ViewPassword", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Configure", "resourceType": "SERVER", "qualifier": "MINE"}, {"action": "Access", "resourceType": "VOLUME", "qualifier": "ANY"}, {"action": "Delete", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "Snapshot", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "Create", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "Attach", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "Configure", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "ManageOwnership", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "Detach", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "ManageBilling", "resourceType": "VOLUME", "qualifier": "MINE"}, {"action": "Access", "resourceType": "IMAGE", "qualifier": "ANY"}, {"action": "ShareLocal", "resourceType": "IMAGE", "qualifier": "MINE"}, {"action": "AccessPublic", "resourceType": "IMAGE", "qualifier": "MINE"}, {"action": "SharePublic", "resourceType": "IMAGE", "qualifier": "MINE"}, {"action": "DefineServerFromPublic", "resourceType": "IMAGE", "qualifier": "ANY"}, {"action": "ManageBilling", "resourceType": "IMAGE", "qualifier": "MINE"}, {"action": "ManageOwnership", "resourceType": "IMAGE", "qualifier": "MINE"}, {"action": "Delete", "resourceType": "IMAGE", "qualifier": "MINE"}, {"action": "DefineServer", "resourceType": "IMAGE", "qualifier": "ANY"}, {"action": "Configure", "resourceType": "IMAGE", "qualifier": "MINE"}]}]}
Headers: date = Mon, 26 Jan 2015 17:17:44 GMT
Headers: connection = keep-alive
Headers: content-type = application/json;charset=UTF-8
Headers: x-es-request = msp0x75f2a183-3f90-4eed-a8df-5bae44484b7e
Headers: server = Dell Cloud Manager

(venv)[brian:...om/bdwilliams/venv/mixcoatl]$ dcm-get admin/Role/2195                                                                                                                      
URL: https://dcm.enstratius.com/api/enstratus/2014-07-30/admin/Role/2195
params = None
Headers: content-encoding = gzip
Headers: transfer-encoding = chunked
Headers: x-es-version = 2014-11-24
Headers: server = Dell Cloud Manager
Headers: connection = keep-alive
Headers: date = Mon, 26 Jan 2015 17:17:53 GMT
Headers: content-type = application/json;charset=UTF-8
Headers: x-es-request = msp0xaa6de6a3-0836-4b72-935d-25049bd5844b
{
  "roles": [
    {
      "acl": [
        {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "Create",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "Delete",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "ShareLocal",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "CreateVolume",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "SharePublic",
          "qualifier": "MINE",
          "resourceType": "SNAPSHOT"
        },
        {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "SERVER"
        },
        {
          "action": "UnPause",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ManageBilling",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ManageUsers",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Resume",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Stop",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ViewLogs",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ManageOwnership",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Pause",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Suspend",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Image",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Terminate",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Reboot",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Monitor",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Start",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "ViewPassword",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "SERVER"
        },
        {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "VOLUME"
        },
        {
          "action": "Delete",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Snapshot",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Create",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Attach",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "ManageOwnership",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Detach",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "ManageBilling",
          "qualifier": "MINE",
          "resourceType": "VOLUME"
        },
        {
          "action": "Access",
          "qualifier": "ANY",
          "resourceType": "IMAGE"
        },
        {
          "action": "ShareLocal",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "AccessPublic",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "SharePublic",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "DefineServerFromPublic",
          "qualifier": "ANY",
          "resourceType": "IMAGE"
        },
        {
          "action": "ManageBilling",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "ManageOwnership",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "Delete",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        },
        {
          "action": "DefineServer",
          "qualifier": "ANY",
          "resourceType": "IMAGE"
        },
        {
          "action": "Configure",
          "qualifier": "MINE",
          "resourceType": "IMAGE"
        }
      ],
      "customer": {
        "customerId": 200
      },
      "description": "test",
      "name": "Test",
      "roleId": 2195,
      "status": "ACTIVE"
    }
  ]
}
(venv)[brian:...om/bdwilliams/venv/mixcoatl]$

I have updated mixcoatl to handle this accordingly.
